import { useEffect, useState } from 'react';
import { Filter, RotateCcw } from 'lucide-react';
import { api } from '../lib/api';

export type ReportFilterState={financialYear:string;month:string;departmentId:string;employeeId:string;dateFrom:string;dateTo:string;status:string;payrollRunId:string};
export const defaultFilters:ReportFilterState={financialYear:'',month:'',departmentId:'',employeeId:'',dateFrom:'',dateTo:'',status:'',payrollRunId:''};
export function ReportFilters({companyId,value,onChange,showDates=false,showStatus=false}:{companyId:string;value:ReportFilterState;onChange:(v:ReportFilterState)=>void;showDates?:boolean;showStatus?:boolean}){
 const [departments,setDepartments]=useState<any[]>([]); const [employees,setEmployees]=useState<any[]>([]); const [runs,setRuns]=useState<any[]>([]);
 useEffect(()=>{Promise.all([api<any>(`/employees/departments?company_id=${companyId}`),api<any>(`/employees?company_id=${companyId}&page=1&limit=100`),api<any>(`/payroll/history?company_id=${companyId}&page=1&limit=100`)]).then(([d,e,r])=>{setDepartments(d.departments||[]);setEmployees(e.employees||[]);setRuns(r.runs||[])}).catch(()=>{});},[companyId]);
 const set=(key:keyof ReportFilterState,val:string)=>onChange({...value,[key]:val});
 const reset=()=>onChange(defaultFilters);
 return <div className="report-filters"><div className="filter-title"><Filter size={16}/><strong>Filters</strong></div><label>Financial Year<select value={value.financialYear} onChange={e=>set('financialYear',e.target.value)}><option value="">All available</option>{[0,1,2].map(i=>{const y=new Date().getFullYear()-i;return <option key={y} value={`${y}-${String((y+1)%100).padStart(2,'0')}`}>{y}-{String((y+1)%100).padStart(2,'0')}</option>})}</select></label><label>Month<select value={value.month} onChange={e=>set('month',e.target.value)}><option value="">All</option>{Array.from({length:12},(_,i)=>i+1).map(m=><option key={m} value={m}>{new Date(Date.UTC(2020,m-1,1)).toLocaleString('en-IN',{month:'long',timeZone:'UTC'})}</option>)}</select></label><label>Department<select value={value.departmentId} onChange={e=>set('departmentId',e.target.value)}><option value="">All departments</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Payroll Run<select value={value.payrollRunId} onChange={e=>set('payrollRunId',e.target.value)}><option value="">Latest available</option>{runs.map(r=><option key={r.id} value={r.id}>{r.payroll_year}-{String(r.payroll_month).padStart(2,'0')} · {r.status}</option>)}</select></label><label>Employee<select value={value.employeeId} onChange={e=>set('employeeId',e.target.value)}><option value="">All employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_id} · {e.first_name} {e.last_name}</option>)}</select></label>{showDates&&<><label>Date From<input type="date" value={value.dateFrom} onChange={e=>set('dateFrom',e.target.value)}/></label><label>Date To<input type="date" value={value.dateTo} onChange={e=>set('dateTo',e.target.value)}/></label></>}{showStatus&&<label>Status<select value={value.status} onChange={e=>set('status',e.target.value)}><option value="">All statuses</option><option>APPROVED</option><option>LOCKED</option><option>GENERATED</option><option>FAILED</option><option>NOT_GENERATED</option></select></label>}<button className="secondary filter-reset" onClick={reset}><RotateCcw size={14}/> Reset</button></div>
}
