import { useMemo, useState } from 'react';
import { ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Columns3, Download, Search } from 'lucide-react';
import { apiBlob } from '../lib/api';

function title(key:string){return key.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function display(v:any,key:string){if(v===null||v===undefined||v==='')return '—';if(typeof v==='number')return Math.round(v).toLocaleString('en-IN');if(key.includes('percentage'))return `${Number(v).toFixed(2)}%`;if(key.includes('date')||key.includes('Date')||key.includes('generated'))return String(v).replace('T',' ').slice(0,19);return String(v);}
export default function ReportTable({rows,total,page,totalPages,loading,onPageChange,exportUrl,requiredColumns=[]}:{rows:any[];total:number;page:number;totalPages:number;loading?:boolean;onPageChange:(n:number)=>void;exportUrl?:string;requiredColumns?:string[]}){
 const columns=useMemo(()=>rows.length?Object.keys(rows[0]):[],[rows]); const [visible,setVisible]=useState<string[]>([]); const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const [sort,setSort]=useState<{key:string;dir:'asc'|'desc'}|null>(null); const active=visible.length?visible:columns; const filtered=rows.filter(r=>!search||Object.values(r).some(v=>String(v??'').toLowerCase().includes(search.toLowerCase()))); const sorted=[...filtered].sort((a,b)=>{if(!sort)return 0;const av=a[sort.key]??'',bv=b[sort.key]??'';const an=Number(av),bn=Number(bv);const cmp=Number.isFinite(an)&&Number.isFinite(bn)&&String(av)!==''&&String(bv)!==''?an-bn:String(av).localeCompare(String(bv));return sort.dir==='asc'?cmp:-cmp;});
 return <div className="report-table-shell"><div className="report-table-tools"><div className="table-search"><Search size={15}/><input placeholder="Search this page…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{exportUrl&&<button className="secondary" onClick={async()=>{const b=await apiBlob(exportUrl);const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='paymate-report.xlsx';a.click();URL.revokeObjectURL(u)}}><Download size={15}/> Excel</button>}<div className="column-picker"><button className="secondary" onClick={()=>setOpen(v=>!v)}><Columns3 size={15}/> Columns</button>{open&&<div className="column-menu">{columns.map(c=><label key={c}><input type="checkbox" checked={active.includes(c)} disabled={requiredColumns.includes(c)} onChange={e=>setVisible(v=>{const base=v.length?v:columns;return e.target.checked?[...new Set([...base,c])]:base.filter(x=>x!==c)})}/>{title(c)}</label>)}</div>}</div></div><div className="report-table-scroll"><table className="report-table"><thead><tr>{active.map(c=><th key={c}><button className="table-sort" onClick={()=>setSort(v=>v?.key===c?{key:c,dir:v.dir==='asc'?'desc':'asc'}:{key:c,dir:'asc'})}>{title(c)} {sort?.key===c?(sort.dir==='asc'?<ChevronUp size={12}/>:<ChevronDown size={12}/>):null}</button></th>)}</tr></thead><tbody>{loading?<tr><td colSpan={Math.max(1,active.length)}><div className="table-skeleton">Loading report…</div></td></tr>:sorted.length?sorted.map((r,i)=><tr key={r.id||r.employee_id_uuid||i}>{active.map(c=><td key={c}>{display(r[c],c)}</td>)}</tr>):<tr><td colSpan={Math.max(1,active.length)}><div className="report-empty">No records found.</div></td></tr>}</tbody></table></div><div className="report-table-footer"><span>{total.toLocaleString('en-IN')} records</span><div><button className="icon-button" disabled={page<=1} onClick={()=>onPageChange(page-1)}><ChevronLeft size={16}/></button><strong>Page {page} of {Math.max(totalPages,1)}</strong><button className="icon-button" disabled={page>=totalPages} onClick={()=>onPageChange(page+1)}><ChevronRight size={16}/></button></div></div></div>
}
