import { useState, type FormEvent } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { ArrowRight, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
export default function Auth({ mode }: { mode: 'login' | 'register' }) {
  const { user } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  if (user) return <Navigate to="/dashboard" replace/>;
  async function resetPassword() { setBusy(true); setError(''); setNotice(''); try { if (!email) throw new Error('Enter your email address first.'); const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/settings/security` }); if (error) throw error; setNotice('If the account exists, a password reset email has been sent.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to send password reset email'); } finally { setBusy(false); } }
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); setNotice(''); try {
    if (mode === 'register') { const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }); if (error) throw error; if (data.session) navigate('/onboarding'); else setNotice('Check your email for a confirmation link, then sign in.'); }
    else { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; navigate('/dashboard'); }
  } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong'); } finally { setBusy(false); } }
  return <div className="auth-page"><div className="auth-aside"><div className="brand"><div className="brand-icon">P</div><span>PayMate<small>PAYROLL WORKSPACE</small></span></div><div><div className="eyebrow">BUILT FOR GROWING TEAMS</div><h1>Payroll starts with a better workspace.</h1><p>Set up your company, manage access, and build a reliable foundation for every payroll cycle.</p></div><div className="auth-foot">SECURE BY DESIGN · POWERED BY SUPABASE</div></div><div className="auth-form-wrap"><form className="auth-card" onSubmit={submit}><div className="eyebrow">WELCOME TO PAYMATE</div><h2>{mode === 'login' ? 'Sign in to your account' : 'Create your account'}</h2><p className="muted">{mode === 'login' ? 'Enter your details to access your workspace.' : 'Start with your account, then set up your company.'}</p>{mode === 'register' && <label>Full name<div className="input-wrap"><UserRound size={18}/><input required minLength={2} value={name} onChange={e => setName(e.target.value)} placeholder="Your full name" autoComplete="name"/></div></label>}<label>Email address<div className="input-wrap"><Mail size={18}/><input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" autoComplete="email"/></div></label><label>Password<div className="input-wrap"><LockKeyhole size={18}/><input type="password" required minLength={6} value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 6 characters" autoComplete={mode === 'login' ? 'current-password' : 'new-password'}/></div></label>{error && <div className="alert error" role="alert">{error}</div>}{notice && <div className="alert success" role="status">{notice}</div>}<button className="primary full" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}<ArrowRight size={18}/></button>{mode === 'login' && <button type="button" className="link-button" disabled={busy} onClick={()=>void resetPassword()}>Forgot password?</button>}<p className="switch">{mode === 'login' ? 'New to PayMate?' : 'Already have an account?'} <Link to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Create an account' : 'Sign in'}</Link></p></form></div></div>;
}
