import { useEffect, useState } from 'react';
import { Download, Eye, Lock, RotateCcw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api, apiBlob } from '../lib/api';
import { useCompany } from '../contexts/CompanyContext';
const money=(v:number)=>`₹${Math.round(Number(v)||0).toLocaleString('en-IN')}`;
const monthName=(m:number)=>new Date(2000,m-1,1).toLocaleString('en-IN',{month:'short'});
export default function PayrollHistory(){const {current}=useCompany();const [runs,setRuns]=useState<any[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [reopenedId,setReopenedId]=useState('');const load=async()=>{if(!current)return;try{setRuns((await api<any>(`/payroll/history?company_id=${current.id}`)).runs||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load payroll history')}};useEffect(()=>{void load()},[current?.id]);
 async function download(id:string,month:number,year:number){if(!current)return;try{const b=await apiBlob(`/payroll/${id}/export?company_id=${current.id}`);const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=`paymate-payroll-${year}-${String(month).padStart(2,'0')}.xlsx`;a.click();URL.revokeObjectURL(u)}catch(e){setError(e instanceof Error?e.message:'Download failed')}}
 async function reopen(r:any){if(!current)return;const reason=window.prompt('Reason for reopening this locked payroll:','Attendance correction required');if(!reason||reason.trim().length<3)return;try{await api(`/payroll/${r.id}/reopen?company_id=${current.id}`,{method:'POST',body:JSON.stringify({reason})});setReopenedId(r.id);setMessage('Payroll reopened as Draft. Recalculate it, submit for review, approve, and lock it again.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to reopen payroll')}}
 return <><div className="page-heading"><div><div className="eyebrow">HISTORY</div><h1>Payroll History</h1><p>Review completed monthly payroll runs and their preserved snapshots.</p></div></div>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message} <Link to={`/payroll?run=${reopenedId}`}>Open payroll</Link></div>}<section className="panel"><div className="table-wrap"><table className="payroll-history-table"><thead><tr><th>Period</th><th>Employees</th><th>Gross</th><th>PF</th><th>PT</th><th>TDS</th><th>Net</th><th>Employer Cost</th><th>Status</th><th>Actions</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td><strong>{monthName(r.payroll_month)} {r.payroll_year}</strong></td><td>{r.employee_count}</td><td>{money(r.gross_total)}</td><td>{money(Number(r.employee_pf_total)+Number(r.employer_pf_total))}</td><td>{money(r.pt_total)}</td><td>{money(r.tds_total)}</td><td className="green-value">{money(r.net_salary_total)}</td><td>{money(r.employer_cost_total)}</td><td><span className={`status-badge ${String(r.status).toLowerCase()}`}>{r.status}</span></td><td><div className="row-actions"><Link className="row-action-icon" title="View" to={`/payroll?run=${r.id}`}><Eye size={15}/></Link><button className="row-action-icon" title="Download" onClick={()=>void download(r.id,r.payroll_month,r.payroll_year)}><Download size={15}/></button>{r.status==='LOCKED'&&<button className="row-action-icon" title="Reopen" onClick={()=>void reopen(r)}><RotateCcw size={15}/></button>}{r.status==='LOCKED'&&<Lock size={15}/>}</div></td></tr>)}</tbody></table></div>{runs.length===0&&<div className="empty-state"><h3>No payroll history</h3><p>Create your first monthly payroll run.</p></div>}</section></>}
