import { useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, Calculator, CheckCircle2, ChevronLeft, ChevronRight, Lock, Plus, RefreshCw, RotateCcw, ShieldAlert, Unlock, XCircle } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { api, apiBlob } from '../lib/api';
import { useCompany } from '../contexts/CompanyContext';
const money=(v:number)=>`₹${Math.round(Number(v)||0).toLocaleString('en-IN')}`;
const monthName=(m:number)=>new Date(2000,m-1,1).toLocaleString('en-IN',{month:'long'});
function periodFromDate(){const d=new Date();return {month:d.getMonth()+1,year:d.getFullYear()};}
export default function Payroll(){
 const {current}=useCompany(); const [searchParams]=useSearchParams(); const now=periodFromDate(); const [month,setMonth]=useState(now.month); const [year,setYear]=useState(now.year); const [run,setRun]=useState<any>(null); const [records,setRecords]=useState<any[]>([]); const [validation,setValidation]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [reopen,setReopen]=useState(false); const [reason,setReason]=useState(''); const [showComponent,setShowComponent]=useState(false); const [components,setComponents]=useState<any[]>([]); const [componentForm,setComponentForm]=useState({employee_id:'',component_id:'',amount:'',reason:'',notes:'',repeat_every_month:false}); const [savingComponent,setSavingComponent]=useState(false);
 const qs=current?`company_id=${current.id}`:'';
 async function loadRun(id?:string){if(!current)return;setLoading(true);setError('');try{let r=id; if(!r){const h=await api<any>(`/payroll/history?${qs}`);r=(h.runs||[]).find((x:any)=>x.payroll_month===month&&x.payroll_year===year)?.id;}if(r){const d=await api<any>(`/payroll/${r}?${qs}`);setRun(d.run);setRecords(d.records||[]);setValidation(d.validation||[]);}else{setRun(null);setRecords([]);setValidation([]);}}catch(e){setError(e instanceof Error?e.message:'Unable to load payroll')}finally{setLoading(false)}}
 useEffect(()=>{void loadRun(searchParams.get('run')||undefined)},[current?.id,month,year,searchParams]);
 async function create(){if(!current)return;setError('');setMessage('');try{const d=await api<any>(`/payroll?${qs}`,{method:'POST',body:JSON.stringify({month,year})});setMessage('Payroll run created.');await loadRun(d.payroll.id);}catch(e){setError(e instanceof Error?e.message:'Unable to create payroll')}}
 async function calculate(){if(!run)return;setLoading(true);setError('');setMessage('');try{await api(`/payroll/${run.id}/calculate?${qs}`,{method:'POST'});setMessage('Payroll recalculated successfully.');await loadRun(run.id);}catch(e){setError(e instanceof Error?e.message:'Unable to calculate payroll')}finally{setLoading(false)}}
 async function action(path:string,body?:any){if(!run)return;setError('');setMessage('');try{await api(`/payroll/${run.id}/${path}?${qs}`,{method:'POST',body:body?JSON.stringify(body):undefined});setMessage(path==='review'?'Payroll submitted for review':path==='approve'?'Payroll approved':path==='lock'?'Payroll locked':path==='reopen'?'Payroll reopened. Recalculate it with current settings, then submit it for review, approve it, and lock it again.':'Payroll action completed.');await loadRun(run.id);}catch(e){setError(e instanceof Error?e.message:'Payroll action failed')}}
 async function exportRun(){if(!run)return;try{const b=await apiBlob(`/payroll/${run.id}/export?${qs}`);const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=`paymate-payroll-${run.payroll_year}-${String(run.payroll_month).padStart(2,'0')}.xlsx`;a.click();URL.revokeObjectURL(u)}catch(e){setError(e instanceof Error?e.message:'Export failed')}}
 async function openAddComponent(){if(!current||!run)return;setError('');try{const result=await api<any>(`/payroll/components?${qs}`);const active=(result.components||[]).filter((item:any)=>item.active);setComponents(active);setComponentForm({employee_id:records[0]?.employee_id||'',component_id:active[0]?.id||'',amount:'',reason:'',notes:'',repeat_every_month:false});setShowComponent(true)}catch(e){setError(e instanceof Error?e.message:'Unable to load payroll components')}}
 async function addComponent(){if(!current||!run)return;setSavingComponent(true);setError('');setMessage('');try{await api(`/payroll/${run.id}/adjustments?${qs}`,{method:'POST',body:JSON.stringify({...componentForm,amount:Number(componentForm.amount)})});setShowComponent(false);setMessage(`Component added and payroll recalculated${componentForm.repeat_every_month?' with monthly repeats':''}. Review, approve, and lock payroll again when ready.`);await loadRun(run.id)}catch(e){setError(e instanceof Error?e.message:'Unable to add payroll component')}finally{setSavingComponent(false)}}
 function shift(delta:number){const d=new Date(year,month-1+delta,1);setMonth(d.getMonth()+1);setYear(d.getFullYear())}
 const totals=useMemo(()=>run?{basic:records.reduce((n,r)=>n+Number(r.basic_salary),0),special:records.reduce((n,r)=>n+Number(r.special_allowance),0)}:null,[run,records]);
 return <><div className="page-heading"><div><div className="eyebrow">PAYROLL PROCESSING</div><h1>Monthly Payroll</h1><p>Process and manage monthly employee payroll for {current?.name}.</p></div><div className="heading-actions"><Link className="secondary" to="/payroll/history">Payroll history</Link>{run&&<button className="secondary" onClick={exportRun}><ArrowDownToLine size={16}/> Export</button>}</div></div>
 <div className="payroll-period-bar"><button onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><div><small>PAYROLL PERIOD</small><strong>{monthName(month)} {year}</strong></div><button onClick={()=>shift(1)}><ChevronRight size={18}/></button><span className={`status-badge ${String(run?.status||'DRAFT').toLowerCase()}`}>{run?.status||'NO RUN'}</span><button className="secondary" onClick={()=>void loadRun(run?.id)}><RefreshCw size={15}/> Refresh</button></div>
 {error&&<div className="alert error"><XCircle size={16}/>{error}</div>}{message&&<div className="alert success"><CheckCircle2 size={16}/>{message}</div>}
 {!run?<section className="panel payroll-empty"><div className="stat-icon blue"><Calculator/></div><h2>No payroll run for {monthName(month)} {year}</h2><p>Create the payroll run to load eligible employees, attendance, salary, PF, PT and TDS.</p><button className="primary" onClick={create}><Plus size={17}/> Create Payroll</button></section>:<>
 <div className="stat-grid payroll-stats"><div className="stat-card"><span>Total Employees</span><strong>{run.employee_count}</strong><small>Included in run</small></div><div className="stat-card"><span>Gross Payroll</span><strong>{money(run.gross_total)}</strong><small>Adjusted gross</small></div><div className="stat-card"><span>Employee PF</span><strong>{money(run.employee_pf_total)}</strong><small>Employee deduction</small></div><div className="stat-card"><span>Employer PF</span><strong>{money(run.employer_pf_total)}</strong><small>Employer contribution</small></div><div className="stat-card"><span>PT</span><strong>{money(run.pt_total)}</strong><small>Professional Tax</small></div><div className="stat-card"><span>TDS</span><strong>{money(run.tds_total)}</strong><small>Current month</small></div><div className="stat-card"><span>Total Deductions</span><strong>{money(run.deduction_total)}</strong><small>Employee deductions</small></div><div className="stat-card"><span>Net Salary</span><strong>{money(run.net_salary_total)}</strong><small>Net payable</small></div><div className="stat-card"><span>Employer Cost</span><strong>{money(run.employer_cost_total)}</strong><small>Gross + employer PF</small></div></div>
 <section className="panel"><div className="panel-title"><div><h3>Payroll controls</h3><span className="muted">Status: {run.status}</span></div><div className="heading-actions">{!['APPROVED','LOCKED'].includes(run.status)&&<button className="primary" onClick={calculate} disabled={loading}><Calculator size={16}/> {loading?'Calculating…':'Calculate Payroll'}</button>}{run.status==='CALCULATED'&&<button className="secondary" onClick={()=>void action('review')}>Submit for Review</button>}{run.status==='UNDER_REVIEW'&&<button className="primary" onClick={()=>void action('approve')}>Approve Payroll</button>}{run.status==='APPROVED'&&<button className="primary" onClick={()=>void action('lock')}><Lock size={15}/> Lock Payroll</button>}{run.status==='LOCKED'&&<button className="secondary" onClick={()=>setReopen(true)}><Unlock size={15}/> Reopen</button>}</div></div></section>
 {validation.length>0&&<section className="panel validation-panel"><div className="panel-title"><h3><ShieldAlert size={18}/> Payroll Validation</h3><span>{validation.filter(v=>v.severity==='ERROR').length} errors · {validation.filter(v=>v.severity==='WARNING').length} warnings</span></div>{validation.map((v:any,i:number)=><div className={`validation-row ${v.severity.toLowerCase()}`} key={v.id||i}><strong>{v.severity}</strong><span>{v.message}</span></div>)}</section>}
 <section className="panel"><div className="panel-title"><div><h3>Payroll employees</h3><span className="muted">Calculated snapshot for {monthName(month)} {year}</span></div><div className="heading-actions">{!['APPROVED','LOCKED'].includes(run.status)&&<button className="primary" onClick={()=>void openAddComponent()}><Plus size={15}/> Add component to employee</button>}<button className="secondary" onClick={calculate} disabled={loading||['APPROVED','LOCKED'].includes(run.status)}><RefreshCw size={15}/> Recalculate</button></div></div><div className="table-wrap payroll-table-wrap"><table className="payroll-table"><thead><tr><th>Employee</th><th>Paid Days</th><th>LOP</th><th>Basic</th><th>Special</th><th>Gross</th><th>Emp. PF</th><th>Er. PF</th><th>PT</th><th>TDS</th><th>Deductions</th><th>Net Salary</th><th>Employer Cost</th><th>Status</th></tr></thead><tbody>{records.map((r:any)=><tr key={r.id}><td><Link className="employee-link" to={`/payroll/${run.id}/employee/${r.employee_id}`}><strong>{r.employees?.first_name} {r.employees?.last_name}</strong><small>{r.employees?.employee_id}</small></Link></td><td>{r.paid_days}</td><td>{r.lop_days}</td><td>{money(r.basic_salary)}</td><td>{money(r.special_allowance)}</td><td><strong>{money(r.adjusted_gross)}</strong></td><td>{money(r.employee_pf)}</td><td>{money(r.employer_pf)}</td><td>{money(r.professional_tax)}</td><td>{money(r.tds)}</td><td>{money(r.total_deductions)}</td><td className="green-value">{money(r.net_salary)}</td><td>{money(r.employer_cost)}</td><td><span className={`status-badge ${String(r.status).toLowerCase()}`}>{r.status}</span></td></tr>)}</tbody></table></div><div className="payroll-total-bar"><span>Basic {money(totals?.basic??0)}</span><span>Special {money(totals?.special??0)}</span><strong>Net {money(run.net_salary_total)}</strong><strong>Employer Cost {money(run.employer_cost_total)}</strong></div></section></>}
 {showComponent&&<div className="modal-backdrop"><div className="confirm-modal"><h2>Add component to employee</h2><p>Choose one employee and enter this payroll component amount for them.</p>{components.length?<div className="form-grid-2"><label className="field full-span"><span>Employee</span><select className="pm-input" value={componentForm.employee_id} onChange={e=>setComponentForm({...componentForm,employee_id:e.target.value})}>{records.map((record:any)=><option key={record.employee_id} value={record.employee_id}>{record.employees?.employee_id} · {record.employees?.first_name} {record.employees?.last_name}</option>)}</select></label><label className="field full-span"><span>Component</span><select className="pm-input" value={componentForm.component_id} onChange={e=>setComponentForm({...componentForm,component_id:e.target.value})}>{components.map((component:any)=><option key={component.id} value={component.id}>{component.name} · {component.direction==='EARNING'?'Earning':'Deduction'}</option>)}</select></label><label className="field"><span>Amount</span><input className="pm-input" type="number" min="0.01" step="0.01" value={componentForm.amount} onChange={e=>setComponentForm({...componentForm,amount:e.target.value})}/></label><label className="field"><span>Reason</span><input className="pm-input" value={componentForm.reason} onChange={e=>setComponentForm({...componentForm,reason:e.target.value})}/></label><label className="field full-span"><span>Notes</span><textarea className="pm-input pm-textarea" value={componentForm.notes} onChange={e=>setComponentForm({...componentForm,notes:e.target.value})}/></label><label className="check-field full-span"><input type="checkbox" checked={componentForm.repeat_every_month} onChange={e=>setComponentForm({...componentForm,repeat_every_month:e.target.checked})}/> Repeat this amount for this employee every month from this payroll month</label></div>:<p>No active components are available. Add one in Payroll Components first.</p>}<div className="drawer-actions"><button className="secondary" onClick={()=>setShowComponent(false)}>Cancel</button><button className="primary" disabled={savingComponent||!components.length||!componentForm.employee_id||!componentForm.component_id||Number(componentForm.amount)<=0||!componentForm.reason.trim()} onClick={()=>void addComponent()}>{savingComponent?'Saving…':'Add and recalculate'}</button></div></div></div>}
 {reopen&&<div className="modal-backdrop"><div className="confirm-modal"><h2>Reopen payroll?</h2><p>This returns payroll to Draft. Recalculate it with current settings before you submit for review, approve, and lock it again. The existing payslip version remains unchanged. Give a reason for the audit trail.</p><textarea className="pm-input pm-textarea" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for reopening"/><div className="drawer-actions"><button className="secondary" onClick={()=>setReopen(false)}>Cancel</button><button className="primary" disabled={reason.trim().length<3} onClick={async()=>{await action('reopen',{reason});setReopen(false);setReason('')}}><RotateCcw size={15}/> Reopen</button></div></div></div>}</>;
}
